Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2021-07, with the labels that each got.

#293 GitHub Data Feature engineering for predicting time to merge
  notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb
Labels: approved, size/XXL

#289 Added size feature to pre existing feature df
  notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb
Labels: approved, size/XL

#317 remove md cell dividers which cause op1st website build to fail
  notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb
Labels: approved, size/S

#316 Update KPI viz nb to content markdown
  docs/content.md
Labels: approved, lgtm, size/XS

#319 Calculate feature importances and select top features
  notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb
Labels: approved, size/XXL

#310 Add metric notebook for probability to fail
  notebooks/data-sources/TestGrid/metrics/probability_to_fail.ipynb
Labels: approved, size/XXL

#320 Update content with KPI viz nb video link
  docs/content.md
Labels: approved, lgtm, size/XS

#328 update list of project maintainers
  .thoth.yaml
Labels: approved, lgtm, size/XS
