Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2021-08, with the labels that each got.

#331 added ttm classifiers
  notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb
  notebooks/data-sources/oc-github-repo/time_to_merge_model.ipynb
Labels: approved, size/XXL, lgtm

#257 Add KPI metric visualization notebook
  notebooks/data-sources/TestGrid/metrics/metrics_visualization.ipynb
Labels: size/XXL

#342 Update the notebook with all tests' test_duration
  notebooks/data-sources/TestGrid/metrics/time_to_test.ipynb
Labels: approved, size/L

#347 add oindrillac to approvers list
  OWNERS
Labels: approved, size/XS, lgtm

#351 Add probability to fail to README
  notebooks/data-sources/TestGrid/metrics/README.md
Labels: approved, size/XS, lgtm

#352 added probability to fail to pipeline
  notebooks/data-sources/TestGrid/metrics/ocp-ci.pipeline
Labels: approved, size/M, lgtm

#348 Deploy time-to-merge model as a service using Seldon
  notebooks/time-to-merge-prediction/model_inference.ipynb
  notebooks/time-to-merge-prediction/seldon-deployment-config.yaml
  notebooks/time-to-merge-prediction/time_to_merge_model.ipynb
Labels: approved, size/XXL
