Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2021-03, with the labels that each got.

#131 Initial implementation of Argo workflows.
  Pipfile
  Pipfile.lock
  manifests/buckets.yaml
  manifests/cronwf.yaml
  manifests/kustomization.yaml
  manifests/wftmpl.yaml
  notebook-executor.sh
Labels: approved

#140 minor CI reconfig, reformatting
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  .prow.yaml
  .thoth.yaml
  notebooks/data-sources/Sippy/stage/sippy_EDA.ipynb
  notebooks/data-sources/TestGrid/background/testgrid_feature_confirmation.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
  notebooks/data-sources/TestGrid/metrics/persistent_failures_analysis.ipynb
  notebooks/data-sources/TestGrid/metrics/test_pass_failures.ipynb
  notebooks/data-sources/TestGrid/testgrid_EDA.ipynb
  notebooks/data-sources/TestGrid/testgrid_indepth_EDA.ipynb
  notebooks/failure-type-classification/background/testgrid_flakiness_detection.ipynb
  notebooks/failure-type-classification/stage/failure_type_classifier.ipynb
Labels: approved

#148 metrics build pass/fail and test blocked and timed out
  notebooks/data-sources/TestGrid/metrics/blocked_timed_out.ipynb
  notebooks/data-sources/TestGrid/metrics/build_pass_failure.ipynb
Labels: approved

#142 Update notebook with Flake Severity
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
Labels: approved

#160 add directory space for ec506 students
  notebooks/data-sources/gcsweb-ci/ec506/ec506.ipynb
Labels: approved

#152 Add percentage of edges for the tests
  notebooks/data-sources/TestGrid/metrics/persistent_failures_analysis.ipynb
Labels: approved

#153 Add KPI notebook for percent test fixed each run
  notebooks/data-sources/TestGrid/metrics/pct_fixed_each_ts.ipynb
Labels: approved

#166 added testgrid metadata exploration nb
  docs/assets/images/metadata-1.png
  docs/assets/images/metadata-2.png
  docs/assets/images/metadata-3.png
  docs/assets/images/metadata-4.png
  docs/assets/images/testgrid_02.png
  docs/assets/images/testgrid_03.png
  notebooks/data-sources/TestGrid/stage/testgrid_metadata_EDA.ipynb
Labels: approved

#167 Update manifests
  manifests/buckets.yaml
  manifests/cronwf.yaml
Labels: approved

#169 Add metric template notebook
  Pipfile
  Pipfile.lock
  notebooks/data-sources/TestGrid/metrics/metric_template.ipynb
Labels: approved

#172 calculate build success and failure rate
  notebooks/data-sources/TestGrid/metrics/build_pass_failure.ipynb
Labels: approved

#168 EDA for remaining testgrid metadata fields
  notebooks/data-sources/TestGrid/testgrid_metadata_EDA.ipynb
Labels: approved

#177 List of all available metrics for Testgrid data
  notebooks/README.md
  notebooks/data-sources/TestGrid/metrics/README.md
  notebooks/data-sources/TestGrid/metrics/build_pass_failure.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
Labels: approved, size/L

#178 update metric notebook template
  notebooks/data-sources/TestGrid/metrics/metric_template.ipynb
Labels: approved, lgtm, size/XL

#188 Add testgrid_metadata_EDA to readme
  notebooks/README.md
Labels: approved, lgtm, size/XS

#189 Update Pipfiles to Python 3.8.
  .aicoe-ci.yaml
  Pipfile
  Pipfile.lock
Labels: approved, lgtm, size/L

#163 Added time duration or time to test metric
  notebooks/data-sources/TestGrid/metrics/time_to_test.ipynb
Labels: approved, size/XL

#196 modified kpi documentation
  notebooks/data-sources/TestGrid/metrics/README.md
Labels: approved, lgtm, size/M

#195 Update number of flakes notebook to template format
  Pipfile
  Pipfile.lock
  notebooks/data-sources/TestGrid/metrics/metric_template.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
Labels: approved, size/XXL
