Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2021-09, with the labels that each got.

#373 Fix broken links
  docs/get-started.md
  docs/how-to-contribute.md
Labels: approved, size/XS

#375 Minor documentation fixes
  docs/content.md
  docs/how-to-contribute.md
Labels: approved, size/S

#371 Add build log clustering model deployment
  notebooks/data-sources/gcsweb-ci/build-logs/model_seldon.ipynb
  notebooks/data-sources/gcsweb-ci/build-logs/seldon_deployment_config.yaml
Labels: approved, size/XL, lgtm

#337 Time to test failure distribution nb
  notebooks/data-sources/TestGrid/metrics/time_to_fail.ipynb
Labels: size/XXL

#378 add Karan to approvers list
  OWNERS
Labels: approved, size/XS, lgtm

#383 add _toc and _config files
  _config.yml
  _toc.yml
Labels: approved, size/L

#389 Changed metric paths
  .env-example
  docs/how-to-contribute.md
  notebooks/data-sources/TestGrid/metrics/blocked_timed_out.ipynb
  notebooks/data-sources/TestGrid/metrics/build_pass_failure.ipynb
  notebooks/data-sources/TestGrid/metrics/correlated_failures.ipynb
  notebooks/data-sources/TestGrid/metrics/metric_template.ipynb
  notebooks/data-sources/TestGrid/metrics/metric_visualization_generic.ipynb
  notebooks/data-sources/TestGrid/metrics/metrics_visualization.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
  notebooks/data-sources/TestGrid/metrics/pct_fixed_each_ts.ipynb
  notebooks/data-sources/TestGrid/metrics/persistent_failures_analysis.ipynb
  notebooks/data-sources/TestGrid/metrics/probability_to_fail.ipynb
  notebooks/data-sources/TestGrid/metrics/test_pass_failures.ipynb
  notebooks/data-sources/TestGrid/metrics/time_to_fail.ipynb
  notebooks/data-sources/TestGrid/metrics/time_to_test.ipynb
Labels: approved, size/XL, lgtm

#390 added notebook to create sql tables
  Pipfile
  Pipfile.lock
  notebooks/data-sources/TestGrid/create_trino_tables.ipynb
Labels: approved, size/XL

#394 changed broken link
  notebooks/time-to-merge-prediction/README.md
Labels: approved, size/XS

#395 Updating the link to White Paper for AppSurify
  docs/aiml-cicd-market-research.md
Labels: approved, size/XS

#385 Update getting started
  README.md
  docs/commands.rst
  docs/data-science-get-started.md
  docs/developer-get-started.md
  docs/get-started.md
  docs/getting-started.rst
  docs/index.rst
  docs/kubernetes-contributor-get-started.md
Labels: approved, size/L, lgtm
