Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2021-05, with the labels that each got.

#256 pipeline validate, modify and exception handling
  notebooks/data-sources/TestGrid/metrics/metric_template.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
  notebooks/data-sources/TestGrid/metrics/ocp-ci.pipeline
  notebooks/data-sources/TestGrid/metrics/validate_pipeline.ipynb
Labels: approved, size/XL

#262 Reorganize content for better discoverability
  .env-example
  README.md
  docs/content.md
  docs/get-started.md
  docs/how-to-contribute.md
Labels: approved, lgtm, size/L

#264 fixing broken links in content markdown
  docs/content.md
Labels: approved, lgtm, size/S

#265 Bugfix: NaN values after df processing
  notebooks/data-sources/TestGrid/metrics/pct_fixed_each_ts.ipynb
Labels: approved, lgtm, size/L

#267 Fix kpi notebooks to solve "job/grid" discrepancy
  notebooks/data-sources/TestGrid/metrics/build_pass_failure.ipynb
  notebooks/data-sources/TestGrid/metrics/pct_fixed_each_ts.ipynb
  notebooks/data-sources/TestGrid/metrics/time_to_test.ipynb
Labels: approved, size/XL

#253 GitHub PR data access and EDA
  data/raw/GitHub/PullRequest.json.gz
  notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb
Labels: approved, size/XL

#270 update the prow resource limits
  .prow.yaml
Labels: approved, lgtm, size/XS

#269 add elyra kfp video
  docs/content.md
Labels: approved, size/XS

#273 Update github section of docs with new links
  docs/content.md
Labels: approved, lgtm, size/XS

#277 Update content.md with video links
  docs/content.md
Labels: approved, lgtm, size/XS

#245 Add notebook with term frequency analysis of build logs
  data/processed/build-logs/periodic-ci-openshift-release-master-ci-4.8-e2e-gcp_vocabulary.txt
  data/raw/gcs/build-metadata/periodic-ci-openshift-release-master-ci-4.8-e2e-gcp_build-logs.csv
  notebooks/README.md
  notebooks/data-sources/gcsweb-ci/build-logs/build_log_EDA.ipynb
  notebooks/data-sources/gcsweb-ci/build-logs/build_log_term_freq.ipynb
Labels: approved, size/XXL

#276 Update bugzilla section of docs with walkthrough link
  docs/content.md
Labels: approved, lgtm, size/XS

#278 Update telemetry section of docs with walkthrough link
  docs/content.md
Labels: approved, lgtm, size/XS
