Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2021-12, with the labels that each got.

#445 Optimal Stopping Point
  notebooks/optimal-stopping-point/osp_helper_functions.ipynb
  notebooks/optimal-stopping-point/osp_model.ipynb
Labels: approved, size/XXL, lgtm

#444 MOC Openstack Demo Notebook
  notebooks/data-sources/moc_openstack_demo.ipynb
Labels: approved, size/L

#391 Add transformers to get features from raw data. Update pipeline.
  Pipfile
  Pipfile.lock
  notebooks/time-to-merge-prediction/time_to_merge_model.ipynb
  src/features/build_features.py
Labels: approved, size/XXL

#458 Add GitHub TTM seldon custom server s2i build directory
  models/github-ttm/.s2i/environment
  models/github-ttm/GitHubTTMModel.py
  models/github-ttm/requirements.txt
  notebooks/time-to-merge-prediction/seldon-deployment-config.yaml
Labels: approved, size/L, lgtm

#460 Update seldon service config and demo notebook
  notebooks/data-sources/gcsweb-ci/build-logs/model_seldon.ipynb
  notebooks/data-sources/gcsweb-ci/build-logs/seldon_deployment_config.yaml
Labels: approved, size/L

#462 Update GitHub TTM Seldon Server
  docs/content.md
  notebooks/time-to-merge-prediction/README.md
  notebooks/time-to-merge-prediction/model_inference.ipynb
  notebooks/time-to-merge-prediction/seldon-deployment-config.yaml
Labels: approved, size/XL, lgtm
