Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2021-06, with the labels that each got.

#285 Add in-depth eda video link
  docs/content.md
Labels: approved, lgtm, size/XS

#290 Add simple KPI metric visualization notebook
  notebooks/data-sources/TestGrid/metrics/metric_visualization_generic.ipynb
Labels: approved, size/XXL

#301 polish and restructure `failure_classification_analysis`
  notebooks/failure-type-classification/README.md
  notebooks/failure-type-classification/failure_type_classifier.ipynb
  notebooks/failure-type-classification/failure_type_functions.ipynb
  notebooks/failure-type-classification/testgrid_flakiness_detection.ipynb
Labels: approved, size/XL

#297 Add function to get test_duration for all tests
  notebooks/data-sources/TestGrid/metrics/metric_template.ipynb
Labels: approved, size/M

#287 Add EDA for distribtion of time to merge
  notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb
Labels: approved, size/XL

#306 remove `test_duration` data duplication
  notebooks/data-sources/TestGrid/metrics/build_pass_failure.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
  notebooks/data-sources/TestGrid/metrics/test_pass_failures.ipynb
Labels: approved, size/XXL

#309 README updates
  notebooks/failure-type-classification/README.md
Labels: approved, size/S
