Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2021-04, with the labels that each got.

#206 fix the python dependencies
  Pipfile.lock
Labels: approved, size/M

#209 Update template for automation
  notebooks/data-sources/TestGrid/metrics/metric_template.ipynb
Labels: approved, lgtm, size/XL

#201 Update persistent_failures_analysis notebook to match template
  notebooks/data-sources/TestGrid/metrics/persistent_failures_analysis.ipynb
Labels: approved, size/XL

#207 Automation pipeline and notebooks
  notebooks/data-sources/TestGrid/metrics/get_raw_data.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
  notebooks/data-sources/TestGrid/metrics/ocp-ci.pipeline
Labels: approved, lgtm, size/XXL

#208 Update correlation_failures to match template and prep for automation
  notebooks/data-sources/TestGrid/metrics/correlated_failures.ipynb
Labels: approved, lgtm, size/XXL

#200 Update test_pass_failures notebook to match metric template + include automation bits
  notebooks/data-sources/TestGrid/metrics/test_pass_failures.ipynb
Labels: approved, size/XL

#211 Update build_pass_failure to match metric template
  notebooks/data-sources/TestGrid/metrics/build_pass_failure.ipynb
Labels: approved, size/XL

#214 fix automation paths in metric notebooks
  notebooks/data-sources/TestGrid/metrics/build_pass_failure.ipynb
  notebooks/data-sources/TestGrid/metrics/correlated_failures.ipynb
  notebooks/data-sources/TestGrid/metrics/metric_template.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
  notebooks/data-sources/TestGrid/metrics/test_pass_failures.ipynb
Labels: approved, lgtm, size/L

#215 Change blocked_timed_out to match metric_template
  notebooks/data-sources/TestGrid/metrics/blocked_timed_out.ipynb
Labels: approved, size/XL

#212 updated time to test KPI to metric template
  notebooks/data-sources/TestGrid/metrics/time_to_test.ipynb
Labels: approved, do-not-merge/hold, size/XL

#216 Documented Elyra KFP pipeline steps
  docs/assets/images/elyra-1.png
  docs/assets/images/elyra-2.png
  docs/assets/images/elyra-3.png
  docs/assets/images/elyra-4.png
  docs/assets/images/elyra-5.png
  docs/assets/images/elyra-6.png
  docs/automating-using-elyra.md
Labels: approved, lgtm, size/M

#210 update pct_fixed_each_ts.ipynb to match template
  notebooks/data-sources/TestGrid/metrics/pct_fixed_each_ts.ipynb
Labels: approved, size/XL

#224 fixing output paths and make ready for automation
  notebooks/data-sources/TestGrid/metrics/blocked_timed_out.ipynb
  notebooks/data-sources/TestGrid/metrics/build_pass_failure.ipynb
  notebooks/data-sources/TestGrid/metrics/correlated_failures.ipynb
  notebooks/data-sources/TestGrid/metrics/get_raw_data.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
  notebooks/data-sources/TestGrid/metrics/pct_fixed_each_ts.ipynb
  notebooks/data-sources/TestGrid/metrics/persistent_failures_analysis.ipynb
  notebooks/data-sources/TestGrid/metrics/test_pass_failures.ipynb
  notebooks/data-sources/TestGrid/metrics/time_to_test.ipynb
Labels: approved, size/XXL

#230 pipeline for all metric notebooks
  notebooks/data-sources/TestGrid/metrics/correlated_failures.ipynb
  notebooks/data-sources/TestGrid/metrics/ocp-ci.pipeline
Labels: approved, lgtm, size/L

#231 Update Readme
  README.md
Labels: approved, lgtm, size/L

#232 Initial work to download and explore build logs from OpenShift CI
  Pipfile
  Pipfile.lock
  data/raw/gcs/build-metadata/periodic-ci-openshift-release-master-ci-4.8-e2e-gcp_build-logs.csv
  notebooks/README.md
  notebooks/data-sources/gcsweb-ci/build-logs/build_log_EDA.ipynb
Labels: approved, size/XXL

#247 Fix the latest black_nb issue due to black latest release
  .pre-commit-config.yaml
  .prow.yaml
  notebooks/failure-type-classification/stage/failure_type_classifier.ipynb
Labels: approved, lgtm, size/XS

#127 Rebuild image using Elyra
  .aicoe-ci.yaml
Labels: approved, size/XS

#248 update automation doc
  docs/automating-using-elyra.md
Labels: approved, lgtm, size/XS

#199 prow-gcs log access
  notebooks/data-sources/gcsweb-ci/prow_archive_discovery.ipynb
Labels: approved, size/XXL

#251 Update default dataset for non-automated runs
  notebooks/data-sources/TestGrid/metrics/correlated_failures.ipynb
  notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb
Labels: approved, lgtm, size/XXL
