Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2022-06, with the labels that each got.

#496 Feature engineering for ttm model for thoth org
  notebooks/time-to-merge-prediction/openshift-origin/github_PR_log_models.ipynb
  notebooks/time-to-merge-prediction/openshift-origin/model_inference.ipynb
  notebooks/time-to-merge-prediction/openshift-origin/seldon-deployment-config.yaml
  notebooks/time-to-merge-prediction/openshift-origin/time_to_merge_model.ipynb
  notebooks/time-to-merge-prediction/thoth-station/thoth_station_feature_engg.ipynb
Labels: approved, size/XXL, lgtm

#501 Update installation of src during s2i build to use https
  models/github-ttm/requirements.txt
Labels: approved, size/XS, lgtm

#498 Append PR data from prescriptions repo
  notebooks/data-sources/github/thoth_PR_data_extraction.ipynb
Labels: approved, size/M, lgtm
