Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2022-01, with the labels that each got.

#464 Add resource requets and limits for github time-to-merge
  notebooks/time-to-merge-prediction/seldon-deployment-config.yaml
Labels: approved, size/S

#466 Reduce log classification service resource requirement
  notebooks/data-sources/gcsweb-ci/build-logs/seldon_deployment_config.yaml
Labels: approved, size/S, lgtm

#468 create trino table from ttm df
  notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb
Labels: approved, size/XXL

#472 added github insights dashboard and jupyterbook
  README.md
  docs/content.md
  docs/data-science-get-started.md
Labels: approved, size/S, lgtm
