Repository aicoe-aiops/ocp-ci-analysis, pull requests merged in 2022-07, with the labels that each got.

#506 Rename output classes returned in github pr ttm prediction service
  models/github-ttm/GitHubTTMModel.py
Labels: approved, size/S, lgtm

#507 Replace links to zero cluster with newer links.
  docs/automating-using-elyra.md
  docs/content.md
  notebooks/README.md
  notebooks/data-sources/TestGrid/metrics/README.md
Labels: approved, size/S, lgtm

#505 added model deployment files for thoth-support
  models/openshift-origin-github-ttm/.s2i/environment
  models/openshift-origin-github-ttm/GitHubTTMModel.py
  models/openshift-origin-github-ttm/requirements.txt
  models/thoth-support-github-ttm/.s2i/environment
  models/thoth-support-github-ttm/ThothGitHubTTMModel.py
  models/thoth-support-github-ttm/requirements.txt
Labels: approved, size/L, lgtm

#518 added aakanksha to approvers
  OWNERS
Labels: approved, size/XS, lgtm

#520 Fix failing imports in openshift origin TTM notebooks
  notebooks/time-to-merge-prediction/openshift-origin/github_PR_log_models.ipynb
  notebooks/time-to-merge-prediction/openshift-origin/model_inference.ipynb
  notebooks/time-to-merge-prediction/openshift-origin/time_to_merge_model.ipynb
Labels: approved, size/S, lgtm

#500 ttm model feature engg and model training
  notebooks/time-to-merge-prediction/thoth-station/thoth_station_feature_engg.ipynb
  notebooks/time-to-merge-prediction/thoth-station/thoth_station_time_to_merge_model.ipynb
Labels: approved, size/XXL, lgtm

#519 Adds framework and docs for workshop and update toc for jupyterbook
  _toc.yml
  docs/assets/images/intro_to_ai4ci.png
  docs/assets/images/intro_to_aiops.png
  docs/assets/images/intro_to_opf.png
  docs/workshop/intro_to_project.md
  docs/workshop/ml_pipeline.md
  docs/workshop/model_deployment.md
  docs/workshop/model_development.md
  docs/workshop/onboarding.md
  docs/workshop/prerequisites.md
  docs/workshop/sql_query_engine.md
  docs/workshop/visualization_dashboard.md
Labels: approved, size/M

#522 Add json exports for thoth support and openshift origin dashboards.
  reports/dashboards/superset/openshift_origin_gh_metrics_v_20220708_201513.json
  reports/dashboards/superset/thoth_support_gh_metrics_v_20220708_201347.json
Labels: approved, size/XXL

#530 Add elyra pipeline for github pr ttm e2e workflow
  notebooks/data-sources/github/openshift_origin_PR_EDA.ipynb
  notebooks/data-sources/github/openshift_origin_data_extraction.ipynb
  notebooks/time-to-merge-prediction/openshift-origin/github-pr-ttm-e2e.pipeline
  notebooks/time-to-merge-prediction/openshift-origin/time_to_merge_model.ipynb
Labels: approved, size/XL, lgtm

#534 Added content for workshop section on model deployment
  docs/assets/images/OpenShift_console1.png
  docs/assets/images/OpenShift_console2.png
  docs/assets/images/OpenShift_console3.png
  docs/assets/images/OpenShift_console4.png
  docs/assets/images/OpenShift_console5.png
  docs/assets/images/OpenShift_console6.png
  docs/assets/images/OpenShift_console7.png
  docs/assets/images/OpenShift_console8.png
  docs/assets/images/OpenShift_console9.png
  docs/assets/images/deployment_config.png
  docs/workshop/model_deployment.md
Labels: approved, size/M, lgtm

#535 And onboarding documentation for workshop
  docs/assets/images/cluster1.png
  docs/assets/images/console-operators.png
  docs/assets/images/console_starting_page.png
  docs/assets/images/jh-container-size.png
  docs/assets/images/jh-workshop.png
  docs/assets/images/seldon.png
  docs/workshop/onboarding.md
Labels: approved, size/M, lgtm

#536 Added generalized workshop TTM model notebooks and pipeline
  notebooks/time-to-merge-prediction/workshop/01_data_collection.ipynb
  notebooks/time-to-merge-prediction/workshop/02_feature_engineering.ipynb
  notebooks/time-to-merge-prediction/workshop/03_model_training.ipynb
  notebooks/time-to-merge-prediction/workshop/end-to-end.pipeline
  notebooks/time-to-merge-prediction/workshop/env_example_workshop
Labels: approved, size/XXL, lgtm

#537 added git setup, model dev, ml pipeline chapters
  _toc.yml
  docs/assets/images/git-setup-fork-repo.png
  docs/assets/images/git-setup-git-account.png
  docs/assets/images/git-setup-pat.png
  docs/assets/images/ml-pipeline-completed-pipeline.png
  docs/assets/images/ml-pipeline-debug-pipeline.png
  docs/assets/images/ml-pipeline-kfp-config.png
  docs/assets/images/ml-pipeline-kfp-ui.png
  docs/assets/images/ml-pipeline-pipeline-nodes.png
  docs/assets/images/ml-pipeline-run-pipeline.png
  docs/assets/images/ml-pipeline-running-nb.png
  docs/assets/images/ml-pipeline-submitted-pipeline.png
  docs/workshop/git_setup.md
  docs/workshop/ml_pipeline.md
  docs/workshop/model_development.md
Labels: approved, size/L, lgtm

#539 Fixed config file with merge conflict
  .buildinfo
Labels: size/XS, lgtm

#541 fixed more html files with merge conflicts
  README.html
  genindex.html
  search.html
Labels: size/XL, lgtm

#542 Added model deployment files
  notebooks/time-to-merge-prediction/workshop/deployment-config.yaml
  notebooks/time-to-merge-prediction/workshop/models/.s2i/environment
  notebooks/time-to-merge-prediction/workshop/models/GitHubTTMModelWorkshop.py
  notebooks/time-to-merge-prediction/workshop/models/requirements.txt
Labels: approved, size/L, lgtm

#544 Modified deployment config for workshop
  notebooks/time-to-merge-prediction/workshop/deployment-config.yaml
Labels: approved, size/S, lgtm

#549 Modified Model-deployment files for workshop
  docs/assets/images/deployment-config1.png
  docs/assets/images/deployment_config.png
  docs/assets/images/signin1.png
  docs/workshop/model_deployment.md
Labels: approved, size/S, lgtm

#548 updated workshop docs
  README.md
  _toc.yml
  docs/assets/images/cloudbeaver-logged-in.png
  docs/assets/images/cloudbeaver-view-table.png
  docs/assets/images/trino-create-table.png
  docs/assets/images/trino-view-table.png
  docs/workshop/model_development.md
  docs/workshop/prerequisites.md
  docs/workshop/sql_query_engine.md
  notebooks/time-to-merge-prediction/workshop/env_example_workshop
Labels: approved, size/L, lgtm

#547 update workshop documentation for onboarding, github setup and visualization dashboards
  docs/assets/images/git-setup-fork-repo.png
  docs/assets/images/git-setup-git-account.png
  docs/assets/images/git-setup-pat.png
  docs/assets/images/superset-charts1.png
  docs/assets/images/superset-charts2.png
  docs/assets/images/superset-charts3.png
  docs/assets/images/superset-dash1.png
  docs/assets/images/superset-dash2.png
  docs/assets/images/superset-dash3.png
  docs/assets/images/superset-dash4.png
  docs/assets/images/superset-dash5.png
  docs/assets/images/superset-dash6.png
  docs/assets/images/superset-dash7.png
  docs/assets/images/superset-dataset1.png
  docs/assets/images/superset-dataset2.png
  docs/assets/images/superset_landing.png
  docs/workshop/git_setup.md
  docs/workshop/onboarding.md
  docs/workshop/visualization_dashboard.md
Labels: approved, size/M, lgtm

#551 added inference file
  notebooks/time-to-merge-prediction/workshop/01_data_collection.ipynb
  notebooks/time-to-merge-prediction/workshop/02_feature_engineering.ipynb
  notebooks/time-to-merge-prediction/workshop/03_model_training.ipynb
  notebooks/time-to-merge-prediction/workshop/04_model_inference.ipynb
Labels: approved, size/XXL, lgtm

#550 Updating pipeline docs for workshop
  docs/assets/images/ml-pipeline-completed-pipeline.png
  docs/assets/images/ml-pipeline-debug-pipeline.png
  docs/assets/images/ml-pipeline-kfp-config.png
  docs/assets/images/ml-pipeline-kfp-ui.png
  docs/assets/images/ml-pipeline-pipeline-nodes.png
  docs/assets/images/ml-pipeline-run-pipeline.png
  docs/assets/images/ml-pipeline-running-nb.png
  docs/assets/images/ml-pipeline-submitted-pipeline.png
  docs/workshop/ml_pipeline.md
Labels: approved, size/XS, lgtm

#554 Added endpoint to deployment file
  notebooks/time-to-merge-prediction/workshop/deployment-config.yaml
Labels: approved, size/XS, lgtm

#563 Add updates to onboarding documentation with feedback from team
  README.md
  docs/assets/images/jh-workshop.png
  docs/workshop/model_development.md
  docs/workshop/onboarding.md
Labels: approved, size/S, lgtm

#564 Adding notebook to read env variable
  notebooks/time-to-merge-prediction/workshop/00_read_env.ipynb
Labels: approved, size/L, lgtm

#565 fixed errors
  notebooks/time-to-merge-prediction/workshop/01_data_collection.ipynb
  notebooks/time-to-merge-prediction/workshop/02_feature_engineering.ipynb
  notebooks/time-to-merge-prediction/workshop/03_model_training.ipynb
Labels: approved, size/XXL, lgtm

#566 Edited env file as new format
  docs/workshop/model_development.md
  notebooks/time-to-merge-prediction/workshop/env_example_workshop
Labels: approved, size/M, lgtm

#567 updated personal access token generation instructions
  docs/assets/images/git-setup-pat.png
  docs/workshop/git_setup.md
  docs/workshop/onboarding.md
Labels: approved, size/S, lgtm

#570 Add a note about the workshop environment used for scale19x.
  docs/workshop/prerequisites.md
Labels: approved, size/XS, lgtm

#569 modified code, docs, pipeline to use kubernetes secret
  docs/assets/images/ml-pipeline-kfp-config.png
  docs/assets/images/ml-pipeline-pipeline-nodes.png
  docs/workshop/ml_pipeline.md
  docs/workshop/model_deployment.md
  docs/workshop/model_development.md
  docs/workshop/sql_query_engine.md
  docs/workshop/visualization_dashboard.md
  notebooks/time-to-merge-prediction/workshop/00_read_env.ipynb
  notebooks/time-to-merge-prediction/workshop/02_feature_engineering.ipynb
  notebooks/time-to-merge-prediction/workshop/03_model_training.ipynb
  notebooks/time-to-merge-prediction/workshop/04_model_inference.ipynb
  notebooks/time-to-merge-prediction/workshop/end-to-end.pipeline
  notebooks/time-to-merge-prediction/workshop/env_example_workshop
Labels: approved, size/M, lgtm

#572 Add env variable test and inference notebook to toc
  _toc.yml
  notebooks/time-to-merge-prediction/workshop/00_read_env.ipynb
Labels: approved, size/XS, lgtm

#574 added parameter to pipeline
  notebooks/time-to-merge-prediction/workshop/end-to-end.pipeline
Labels: approved, size/XS, lgtm

#573 Introduction to data science workflow materials
  _toc.yml
  notebooks/time-to-merge-prediction/workshop/Bike.csv
  notebooks/time-to-merge-prediction/workshop/intro_to_jupyternotebooks.ipynb
Labels: approved, size/XXL, lgtm

#576 Add slides for Openinfra foundation collaboration
  docs/aiops_for_community_health.pdf
Labels: approved, size/XS
